Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.provider :virtualbox do |vb|
    vb.customize [ 'modifyvm', :id, '--name', 'demo-00' ]
  config.vm.define "web" do |web|
      web.vm.box = "ubuntu/xenial64" 
  end
  config.vm.provision "shell", path: "script.sh"
  config.vm.define "db" do |db|
      db.vm.box = "ubuntu/xenial64"
  end
